coverage:
  precision: 1
  round: nearest
  range: "10...90"

  status:
    project:
      default:
        target: 70%
    patch:
      default:
        target: 60%
    changes: no

comment:
  # diff, changes, footer, reach, flags, suggestions
  layout: "header, files"
